<?php

namespace App\Modelo\Servicios;

use App\Horarios\Execptions\HoraNoValidaException;
use App\Servicios\Pista;
use PDO;

require_once __DIR__ . "/../../../datosConexionBD.php";
require_once __DIR__ . "/../../../datosConfiguracion.php";

class PistaDAOMySQL extends PistaDAO
{

    public function __construct()
    {
        $this->setConexion(
            new PDO(
                "mysql:host=" . HOSTBD .
                ";dbname=" . NOMBREBD, USUARIOBD, PASSBD
            )
        );

        $this->getConexion()->setAttribute(
            \PDO::ATTR_ERRMODE,
            \PDO::ERRMODE_EXCEPTION
        );
    }

    /**
     * @throws PistaNoEncontradaException
     */
    public function leerPista(int $idPista): ?Pista
    {
        $query = "SELECT * FROM pista WHERE IDPISTA= ?";
        $sentencia = $this->getConexion()->prepare($query);
        $sentencia->bindParam(1, $idPista);
        $sentencia->execute();

        if (($fila = $sentencia->fetch())) {
            return new Pista(
                $fila['IDPISTA'],
                $fila['PRECIO'],
                $fila['LUZ'],
                $fila['PRECIOLUZ'],
                $fila['TIPOPISTA'],
                $fila['CUBIERTA'],
                $fila['DISPONIBLE'],
                $fila['RESERVASPISTAMENSUALES'],
            );
        } else {
            throw new PistaNoEncontradaException("La pista no existe en la base de datos.");
        }
    }

    public function modificarPista(Pista $pista): ?Pista
    {
        $query = "UPDATE pista SET PRECIO=:precio, LUZ=:luz, PRECIOLUZ=:precioLuz, 
                 TIPOPISTA=:tipoPista, CUBIERTA=:cubierta, DISPONIBLE=:disponible,
                 RESERVASPISTAMENSUALES=:reservasPistaMensuales WHERE IDPISTA=:idPista";
        $sentencia = $this->getConexion()->prepare($query);
        $sentencia->bindValue("precio", $pista->getPrecio());
        $sentencia->bindValue("luz", $pista->getLuz());
        $sentencia->bindValue("precioLuz", $pista->getPrecioLuz());
        $sentencia->bindValue("tipoPista", $pista->getTipoPista());
        $sentencia->bindValue("cubierta", $pista->getCubierta());
        $sentencia->bindValue("disponible", $pista->getDisponible());
        $sentencia->bindValue("reservasPistaMensuales", $pista->getReservasPistasMensual());

        $resultado = $sentencia->execute();

        if ($resultado) {
            return $pista;
        } else {
            return null;
        }
    }

    public function modificarTodasLasPistas(array $elementosAModificar)
    {
        $query = "UPDATE pista SET ";

        if (isset($elementosAModificar['precio'])) {
            $query .= "PRECIO=:precio,";
        }
        if (isset($elementosAModificar['luz'])) {
            $query .= "LUZ=:luz,";
        }
        if (isset($elementosAModificar['precioLuz'])) {
            $query .= "PRECIOLUZ=:precioLuz,";
        }
        if (isset($elementosAModificar['tipoPista'])) {
            $query .= "TIPOPISTA=:tipoPista,";
        }
        if (isset($elementosAModificar['cubierta'])) {
            $query .= "CUBIERTA=:cubierta,";
        }
        if (isset($elementosAModificar['disponible'])) {
            $query .= "DISPONIBLE=:disponible,";
        }
        if (isset($elementosAModificar['reservasPistaMensual'])) {
            $query .= "RESERVASPISTAMENSUAL=:reservasPistaMensual,";
        }

        $query = substr($query, 0, -1);
        $sentencia = $this->getConexion()->prepare($query);

        if (isset($elementosAModificar['precio'])) {
            $sentencia->bindParam("precio", $elementosAModificar['precio']);
        }
        if (isset($elementosAModificar['luz'])) {
            $sentencia->bindParam("luz", $elementosAModificar['luz']);
        }
        if (isset($elementosAModificar['precioLuz'])) {
            $sentencia->bindParam("precioLuz", $elementosAModificar['precioLuz']);
        }
        if (isset($elementosAModificar['tipoPista'])) {
            $sentencia->bindParam("tipoPista", $elementosAModificar['tipoPista']);
        }
        if (isset($elementosAModificar['cubierta'])) {
            $sentencia->bindParam("cubierta", $elementosAModificar['cubierta']);
        }
        if (isset($elementosAModificar['disponible'])) {
            $sentencia->bindParam("disponible", $elementosAModificar['disponible']);
        }
        if (isset($elementosAModificar['reservasPistaMensual'])) {
            $sentencia->bindParam("reservasPistaMensual", $elementosAModificar['reservasPistaMensual']);
        }

        try {
            $sentencia->execute();
        } catch (\PDOException $e) {
            throw new ActualizarPistasException("No se han podido actualizar las pistas");
        }
    }

    public function borrarPistaPorId(int $idPista): ?Pista
    {
        parent::borrarPistaPorId($idPista); // TODO: Change the autogenerated stub
    }

    public function borrarPista(Pista $pista): ?Pista
    {
        parent::borrarPista($pista); // TODO: Change the autogenerated stub
    }

    public function insertarPista(Pista $pista): ?Pista
    {
        parent::insertarPista($pista); // TODO: Change the autogenerated stub
    }

    public function leerTodasLasPistas(): ?array
    {
        parent::leerTodasLasPistas(); // TODO: Change the autogenerated stub
    }

    public function obtenerRangoPistas(int $inicio, int $numeroResultados = NUMERODERESULTADOSPORPAGINA): array
    {
        parent::obtenerRangoPistas($inicio, $numeroResultados); // TODO: Change the autogenerated stub
    }

    public function convertirArrayPistas(array $datosPista): ?Pista
    {
    }

    public function existeIdPista($idPista): bool
    {
        $query = "SELECT * FROM pista WHERE IDPISTA=?";
        $sentencia = $this->getConexion()->prepare($query);
        $sentencia->bindParam(1, $idPista);
        $sentencia->execute();

        return ($sentencia->execute());
    }
}